### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by Dannyx1604** [Moonlight-Panel/Moonlight#127]
Die Übersetzungen von Englisch auf Deutsch klappen nicht bei den Überschriften und auch teilweise bei den Descriptions für die Webspaces:![20230522_195221.jpg](https://github.com/Moonlight-Panel/Moonlight/assets/107413165/bc7d3420-3b0c-4ed0-8b80-4d5e2a8087fa)

**Comment by Marcel-Baumgartner** [comment]
Hey, first english please, second this happens due to the translations not being fully done
