### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by DatGamet** [Moonlight-Panel/Moonlight#136]
Man kann mit 2 Accounts den gleichen Discord Account verlinken. Die Verlinkung mit dem Discord Account wird nicht entfernt, sobald man sich mit einem neuen Account verbindet.

Man kann aber über Discord > Einstellungen > Authorisierte Apps die Verknüpfung entfernen.

**Comment by mxritzdev** [comment]
Closed because this is still about v1
