### ISSUE TITLE
Support Chat - Timestamps

### ISSUE THREAD

**Issue by DatGamet** [Moonlight-Panel/Moonlight#152]
Die Timestamps der Support Chats sind teilweise etwas komisch angezeigt.
Dort steht dann "42 vor Minuten"
![Screenshot 2023-06-09 235638](https://github.com/Moonlight-Panel/Moonlight/assets/113996043/ec57044f-5d35-4d7d-9c5a-041ab72667a4)

**Comment by Marcel-Baumgartner** [comment]
English please ^^

**Comment by DatGamet** [comment]
._.

**Comment by Dannyx1604** [comment]
I had to go through this too [https://github.com/Moonlight-Panel/Moonlight/issues/127](https://github.com/Moonlight-Panel/Moonlight/issues/127)

**Comment by Marcel-Baumgartner** [comment]
Will be rewritten in the new ticket system so i'll mark this as fixed
