### ISSUE TITLE
Create a Server

### ISSUE THREAD

**Issue by SnyderWillCode** [Moonlight-Panel/Moonlight#153]
So I have been wanting to make something like this but in PHP without using Pterodactyl API.
This project looks really cool, I just wanted to know where the Create Server code is, because I want to see how the API is being used to make a server.

**Comment by Marcel-Baumgartner** [comment]
Hey hey, wings related api calls are made in the ServerService.cs. You also need to handle wings server and egg data requests as we did in the ServersController.cs

**Comment by SnyderWillCode** [comment]
Thanks for the response. I will check it out.
