### ISSUE TITLE
Hi im the owner of PteroController and i kinda need your help can you give me your discord or add me on discord?

### ISSUE THREAD

**Issue by NaysKutzu** [Moonlight-Panel/Moonlight#154]
My discord: `NaysKutzu#5375`
Im also using c# winforms and i kinda need ur help

**Comment by NaysKutzu** [comment]
or can you help me here https://stackoverflow.com/questions/76445813/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-c-sharp

**Comment by Spielepapagei** [comment]
Sorry, but this is _kinda_ the wrong place here this is for issues from Moonlight we are no coding help Center.

Please look on a Coding help Discord sutch like.
https://discord.gg/devsky [this one is in German]
