### ISSUE TITLE
Mobile App?

### ISSUE THREAD

**Issue by Dannyx1604** [Moonlight-Panel/Moonlight#155]
Will the source code of the mobile app be released at some time? 

(_Or maybe there will be one app that lets you insert a panel url and then you can control the servers with it, so that there is one app for all moonlight instances_)

**Comment by Daniel-Balk** [comment]
The current/old app is just a webview and will be discontinued. The new one is going to be an open source app. The panel url will be stored as a constant in the code. But this project is planned and is currently not in development.

**Comment by Dannyx1604** [comment]
Ah, nice
