### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by Bensonheimer992** [Moonlight-Panel/Moonlight#176]
Even if it's not a big bug, it bothers me that the popups always have the wrong theme
![grafik](https://github.com/Moonlight-Panel/Moonlight/assets/101340634/b6bf3571-3759-4eba-ad24-5f1a5a41e4ca)

**Comment by Marcel-Baumgartner** [comment]
This only occures when the users internet connection is slow so the theme has not loaded when launching the popup
