### ISSUE TITLE
Bug with the selection of the java version at the Minecraft Images

### ISSUE THREAD

**Issue by Dannyx1604** [Moonlight-Panel/Moonlight#190]
The java version seems not to be correct everytime I create a new server using a Minecraft Image. I then have to change it from the Admin panel.

**Comment by Marcel-Baumgartner** [comment]
Is the minecraft17 docker image marked as the default image in your paper image?

**Comment by Dannyx1604** [comment]
Yes, it is!

[20230624_114502.jpg](https://github.com/Moonlight-Panel/Moonlight/assets/107413165/6d7e869b-732d-43c4-b8d7-40e41d128f85)

**Comment by Marcel-Baumgartner** [comment]
hmmm okay. i am trying to replicate this wehn i have time for it and i will notify you if i found anything

**Comment by Marcel-Baumgartner** [comment]
Should be fixed in the MinecraftVersions plugin
