### ISSUE TITLE
Minecraft version question

### ISSUE THREAD

**Issue by Adz250** [Moonlight-Panel/Moonlight#220]
Hi, 
i haven’t installed the panel yet but i was just wondering about version changer, will i be able to select version between spigot and paper and other mod packs or is it just paper version if it’s would be possible to add spigot in it? 

thank you for your answer in advance.

**Comment by Dannyx1604** [comment]
Hello, if you just have a question, please ask in the [Discord Server](https://discord.gg/u7DZ4CM2r5)
