### ISSUE TITLE
Dont load the Background-Image on a slow Internet Connection 

### ISSUE THREAD

**Issue by Moritz-Deiaco** [Moonlight-Panel/Moonlight#244]
On slow Internet (so basically my WiFi) the Panel takes really long to load because of the Background-Image. Maybe you could improve the Panels Performance by not loading the Image on a slow Internet Connection

**Comment by Moritz-Deiaco** [comment]
Or maybe add a setting to mannually turn Background-Images off.

**Comment by Marcel-Baumgartner** [comment]
Improved in #283 for default resources
