### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by Syntax3rror404** [Moonlight-Panel/Moonlight#245]
What about Kubernetes support? A implementation for that would be awesome!!!!

**Comment by Marcel-Baumgartner** [comment]
Can you describe how exactly you want a implementation? So, what can be done using this implementation, how should it be designed?

**Comment by Syntax3rror404** [comment]
Of course! The same app as it is, only that instead of using Docker containers, it uses the Kubernetes API to spin up and manage the containers. In the end, Moonlight should be able to be installed as a Helm Chart.

**Comment by Marcel-Baumgartner** [comment]
We will discuss the feature request inside the development team and will tell you if we will implemented it

**Comment by Marcel-Baumgartner** [comment]
We wont implement it in the near future. We have not enough time :/
