### ISSUE TITLE
[Feature Request]: Add TOTP Code to 2-FA Activation menu

### ISSUE THREAD

**Issue by Timongcraft** [Moonlight-Panel/Moonlight#247]
The method for activating 2FA only provides a QR code to scan. My issue with this is that I can't simply paste the code into Bitwarden.

~~I also tried scanning the code with the Bitwarden phone app, but it didn't work. Even when I manually entered the Secret into the app, I received an error upon saving. This was an error on my part.~~

You're solution to it:

Just add the totp code/secret whatever to the activation screen like this:
![image](https://github.com/Moonlight-Panel/Moonlight/assets/77288029/48d43a9d-f94f-451f-a817-979d210af09b)

**Comment by Marcel-Baumgartner** [comment]
Implemented in #285

**Comment by Marcel-Baumgartner** [comment]
![image](https://github.com/Moonlight-Panel/Moonlight/assets/68913099/fef44b87-b28b-43fa-bac8-17f8baddf27b)
