### ISSUE TITLE
Potential security Vulnerability

### ISSUE THREAD

**Issue by Spielepapagei** [Moonlight-Panel/Moonlight#253]
suggestion Change it  so that this feature is deactivated after x minutes. Reactivate after a restart if no user exists. 
_completely deactivate all registrations_

Moonlight/App/Services/UserService.cs
![Screenshot_20230808-143024.png](https://github.com/Moonlight-Panel/Moonlight/assets/74091754/d206c265-4e22-4daf-b727-cbc5f461be7f)

**Comment by Marcel-Baumgartner** [comment]
This will be at only one time true. If no user has been registered. After that it will be always false

**Comment by Marcel-Baumgartner** [comment]
![image](https://github.com/Moonlight-Panel/Moonlight/assets/68913099/9800ab50-2338-450b-9068-0af9a139a937)

Done in #271
