### ISSUE TITLE
security logs hide 1/2 characters of password

### ISSUE THREAD

**Issue by realspinelle** [Moonlight-Panel/Moonlight#262]
in logs hide 1/2 characters of password on password attempts ( i dont want my friends to almost know my password if i type it wrong )

**Comment by Moritz-Deiaco** [comment]
Good idea...

**Comment by Marcel-Baumgartner** [comment]
Indeed a good idea, we will implement it soon. The implementation will only work for new login attempts. Old logs will be untouched

**Comment by Marcel-Baumgartner** [comment]
Done in #270
