### ISSUE TITLE
Cannot delete a Node. 

### ISSUE THREAD

**Issue by Voroniyx** [Moonlight-Panel/Moonlight#264]
Using the Moonlight Version shown in the first picture, it is not possible to delete Nodes. In the second picture u can see the error. 
Hopefully it is possible to create a fix with this information. For further questions you are always welcome to come back to me
![image](https://github.com/Moonlight-Panel/Moonlight/assets/91881990/e0b31ce3-e265-4cb3-881f-d2af1f768677)
![image](https://github.com/Moonlight-Panel/Moonlight/assets/91881990/aea8c69d-a789-4153-adb9-11d2b3dacd87)

**Comment by Marcel-Baumgartner** [comment]
You cannot delete the node because of allocations still related to the node. If you delete the allocations, you will be able to delete the node as well. Deleting nodes will be improved soon

**Comment by Voroniyx** [comment]
ok, good to know. would be good if there is a message for such a thing that says what you still have to remove, but if you say you are working on it I have full confidence in you

**Comment by Marcel-Baumgartner** [comment]
Fixed in v2
