### ISSUE TITLE
some enhancement

### ISSUE THREAD

**Issue by realspinelle** [Moonlight-Panel/Moonlight#265]
- [x] Move changelog to admin for me the user side doesnt need to know change logs
![image](https://github.com/Moonlight-Panel/Moonlight/assets/39035551/2b79e5ff-fa9c-4820-9379-fc40f953f05c)
- [x] Add a gap here  ![image](https://github.com/Moonlight-Panel/Moonlight/assets/39035551/afdfbc96-b37f-46bc-918f-81e3523d244e)
- [ ] When a server disk space is full and you try to start a server after checking disk space add a message that says that the disk is full ![image](https://github.com/Moonlight-Panel/Moonlight/assets/39035551/98cab1e6-51bd-4cb5-9794-304eca29f97d)
- [x] Except if its intended ? Remove the layers of accordion ![image](https://github.com/Moonlight-Panel/Moonlight/assets/39035551/6c7d3f88-33fc-47bc-9e77-530230f1c912)
- [x] Set unsorted servers to open by default (i did it already i just need to do a pull request) ![image](https://github.com/Moonlight-Panel/Moonlight/assets/39035551/beef9253-aa1e-4bf5-b50c-8ef275572ae0)

Some ideas :smile:

**Comment by Marcel-Baumgartner** [comment]
Thanks for your feedback. The server view page will be redesigned anyways, so we will include your ideas. to the config nested thing, this is indeed intentional. The server disk warning will be implemented like that:

![image](https://github.com/Moonlight-Panel/Moonlight/assets/68913099/cc0b8f40-0c10-4ffd-9575-0189af9219a2)

**Comment by Marcel-Baumgartner** [comment]
changelog done in #269

**Comment by Marcel-Baumgartner** [comment]
![image](https://github.com/Moonlight-Panel/Moonlight/assets/68913099/f14a66fe-28c3-4a50-95a5-64c820f96705)
Network tab as of the release that will come out today ^^

**Comment by realspinelle** [comment]
Finished to me

**Comment by steve-1507** [comment]
Why should the users not be able to read the changelog?
