### ISSUE TITLE
Mobile Browser Server specs and Power Buttons overlapping

### ISSUE THREAD

**Issue by Dannyx1604** [Moonlight-Panel/Moonlight#279]
In the mobile Browser the server specs and the power buttons overlap (see image![20230819_171003.jpg](https://github.com/Moonlight-Panel/Moonlight/assets/107413165/14f7bc0e-18f6-4898-bcc4-5ffc3ca7602b)

)

**Comment by mxritzdev** [comment]
Closed because this is still about v1
