### ISSUE TITLE
New server deployment not asking for ip and port allocation

### ISSUE THREAD

**Issue by SNOW-NOVA** [Moonlight-Panel/Moonlight#306]
Hi Team,

When deploying a new server, the configuration screen is not requesting networking information to be selected during the creation process. This is probably due to the following below things that I have noticed.

1. When setting up a node, there is no option to attach any additional ip allocations / addresses to that node to be utilised for servers or any other services, that you may wish to host in future. 

2. During the creation of a new server, the default ip address and an automatically selected port on the node is assigned to the new server by default. There is no option to select a different port and more importantly assign multiple ports as required by games like rust etc. The only way to attach additional ports is to edit after creation. Then the server can be powered on.

The first point may not be part of your roadmap and/or and maybe added as a feature in future. However the second point potentially could be an option that may have been overlooked?

**Comment by Marcel-Baumgartner** [comment]
Assigning multiple ports is possible. Moonlight images have an option to specify how many ports an image needs. Assigning ports when setting up a node should be obvios

**Comment by Marcel-Baumgartner** [comment]
If you want to use the additional ports in an image without having the user to specify the port himself you can use the ML_PORT_X enviroment variables
