### ISSUE TITLE
Feature for Admins: Send a Profile edit Request

### ISSUE THREAD

**Issue by Moritz-Deiaco** [Moonlight-Panel/Moonlight#312]
Is it possible to create a feature that prompts the user on his next login to change his Names or Adress, before they can use the panel again? (Thinking about something like the Totp Code input)

**Comment by Marcel-Baumgartner** [comment]
This is already a feature. Just set the state to DataPending or PasswordPending

**Comment by Moritz-Deiaco** [comment]
Then, the page crashes

**Comment by Marcel-Baumgartner** [comment]
It does not. Only sometomes when the db context is already used
