### ISSUE TITLE
TAB Navigation Highlight

### ISSUE THREAD

**Issue by steve-1507** [Moonlight-Panel/Moonlight#314]
When selecting a button with TAB, items in the sidebar and at the bottom of the page to not get highlightes, while objects in the center of the page do correctly get highlighted

![monlight select](https://github.com/Moonlight-Panel/Moonlight/assets/62237118/57fc5e18-b71f-4e73-abc7-c42685995d28)

In the attachment, I have marked all areas that do not correctly get highlighted in red, while areas that do correctly highlighted are green

**Comment by Marcel-Baumgartner** [comment]
Moonlight does not support tab controls

**Comment by steve-1507** [comment]
![grafik](https://github.com/Moonlight-Panel/Moonlight/assets/62237118/ed4325ba-4c21-4656-9dbe-6870cce7a9e7)

**Comment by steve-1507** [comment]
for not specifically implementing it, it works actually pretty well
