### ISSUE TITLE
Google Fonts proxy

### ISSUE THREAD

**Issue by gOOvER** [Moonlight-Panel/Moonlight#344]
At the moment google fonts are used without proxy, which is absolutely against the GDPR.

I would welcome it if a google fonts proxy loaded the fonts

**Comment by Marcel-Baumgartner** [comment]
We could do something like with the gravatar profile pictures which are proxied using an api endpoint in moonlight itself

**Comment by Marcel-Baumgartner** [comment]
Done in #345
