### ISSUE TITLE
All servers have problem with Java?

### ISSUE THREAD

**Issue by KatiaSishost** [Moonlight-Panel/Moonlight#363]
Every time I create a server I get the Java error, I have all the plugins installed.

`

 Moonlight  Checking disk space
 Moonlight  Updating config files
 Moonlight  Checking file permissions
 Moonlight  Downloading server image
Pulling from moonlightpanel/images 
Status: Image is up to date for moonlightpanel/images:minecraft16 
Digest: sha256:15f032259c295b74eecc9c00b614a11554b681f37b93a18986821631eeed610b 
 Moonlight  Downloaded server image
Java Version:
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
Minecraft 1.19 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/
 Moonlight  ---------- Detected server process in a crashed state! ----------
 Moonlight  Exit code: 1
 Moonlight  Out of memory: false
 Moonlight  Checking disk space
 Moonlight  Updating config files
 Moonlight  Checking file permissions
 Moonlight  Downloading server image
Pulling from moonlightpanel/images 
Digest: sha256:15f032259c295b74eecc9c00b614a11554b681f37b93a18986821631eeed610b 
Status: Image is up to date for moonlightpanel/images:minecraft16 
 Moonlight  Downloaded server image
Java Version:
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
Minecraft 1.19 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/
 Moonlight  ---------- Detected server process in a crashed state! ----------
 Moonlight  Exit code: 1
 Moonlight  Out of memory: false
 Moonlight  Aborting automatic restart, last crash occurred less than 60 seconds ago.
`

**Comment by Marcel-Baumgartner** [comment]
Have you used the version switcher to change the version of your minecraft server?

**Comment by gOOvER** [comment]
Problem is on your side:

`Minecraft 1.19 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/`
