### ISSUE TITLE
[enhancement] database data "mover"

### ISSUE THREAD

**Issue by Moritz-Deiaco** [Moonlight-Panel/Moonlight#364]
Add a way in v2 to easily move the database data from the old database to the new one.

**Comment by Marcel-Baumgartner** [comment]
Please specify more details for the feature

**Comment by Moritz-Deiaco** [comment]
Lets say i want to Switch to another Database, but dont want to move all the data manually from the old to the new one. So there could be a form, where i input the new db credentials and Moonlight now:
- saves the old data on the drive in a sql File 
- automatically edits the config 
- restarts (if needed)
- and executes the sql File on the new db
This would be a really useful feature in my opinion.

**Comment by Marcel-Baumgartner** [comment]
This is not a feature moonlight needs. Most people have phpmyadmin or dbeaver so it will not be implemented
