### ISSUE TITLE
[V2] Some first bugs i encountered

### ISSUE THREAD

**Issue by mxritzdev** [Moonlight-Panel/Moonlight#375]
### Current Behavior

- If you want to delete an image, and another user is on the image edit/view page or you have it open on another tab , the page will crash
- You cannot edit a file 

### Expected Behavior

- the image should be deleted
- the file should be edited

### Steps to Reproduce

explained in current Behavior

### Panel Version

v2 early access (v1 i guess)

### Daemon Version

v2 early access (v1 i guess)

### Wings Version

---

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
The file editing has been fixed here https://github.com/Moonlight-Panel/MoonlightDaemon/pull/2

**Comment by Masu-Baumgartner** [comment]
Fixed in https://github.com/Moonlight-Panel/Moonlight/pull/380
