### ISSUE TITLE
Autosetup Daemon use email letsencrypt@moonlightpanel.xyz

### ISSUE THREAD

**Issue by gOOvER** [Moonlight-Panel/Moonlight#378]
### Current Behavior

When you want to setup a node and copy the command, the cmd uses `--use-email letsencrypt@moonlightpanel.xyz`

### Expected Behavior

the command should use Admin eMail 

### Steps to Reproduce

autosetup node

### Panel Version

2.0.0

### Daemon Version

2.0.0

### Wings Version

none

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by mxritzdev** [comment]
Maybe this email was specifically set up for this usage

**Comment by gOOvER** [comment]
> Maybe this email was specifically set up for this usage

i dont want to use an other email for the cert. It doesnt matter, which email is used, but i want to use my in my certs :)

Masu; mb check, if the deamon should be installed on the same Server as the panel; then you can only copy over the certs allready installed

**Comment by mxritzdev** [comment]
> > Maybe this email was specifically set up for this usage
> 
> i dont want to use an other email for the cert. It doesnt matter, which email is used, but i want to use my in my certs :)
> 
> Masu; mb check, if the deamon should be installed on the same Server as the panel; then you can only copy over the certs allready installed

You could just replace it with your own email

**Comment by Masu-Baumgartner** [comment]
> > Maybe this email was specifically set up for this usage
> 
> i dont want to use an other email for the cert. It doesnt matter, which email is used, but i want to use my in my certs :)
> 
> Masu; mb check, if the deamon should be installed on the same Server as the panel; then you can only copy over the certs allready installed

it is mentioned in the getting started guide that if you are already using lets encrypt with the same domain on the same server, that you should add the `--skip-lets-encrypt` flag. But i can add a check if the cert already exists if it becomes a problem. Also i'll used this email as a dummy email for testing, i will just use the current users email when generating the command

**Comment by Masu-Baumgartner** [comment]
Fixed in https://github.com/Moonlight-Panel/Moonlight/pull/380
