### ISSUE TITLE
Database error on Setup 

### ISSUE THREAD

**Issue by jesperrichert** [Moonlight-Panel/Moonlight#379]
### Current Behavior

If i use my Database or the Internal i get an error like this 
![Screenshot_20240410-132757](https://github.com/Moonlight-Panel/Moonlight/assets/94371018/03410d3a-0611-453a-82d4-3dd8370a8fde)

### Expected Behavior

Maybe the Installer have a problem with the Database setup

### Steps to Reproduce

I have try to use other Databases

### Panel Version

2.0.0

### Daemon Version

2.0.0

### Wings Version

1.11.x

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
Fixed in https://github.com/Moonlight-Panel/Installer/pull/4
