### ISSUE TITLE
Craches  and Node Setup Problems

### ISSUE THREAD

**Issue by jesperrichert** [Moonlight-Panel/Moonlight#383]
### Current Behavior

If i will setup a node like the Command then the Command will not set correct setting in the json file from the Deamon Config. 
Like FQN or Token will not set and saved.

IF i want to delete my server if i have an node but the **node** is not running

### Expected Behavior

I can't delete my server on the node 

### Steps to Reproduce

i have set it in the config

### Panel Version

2.0.0

### Daemon Version

2.0.0

### Wings Version

1.11.x

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by jesperrichert** [comment]
And now my node is wrking. my server report this error.
![image](https://github.com/Moonlight-Panel/Moonlight/assets/94371018/4dcab4b1-f53e-4171-912f-230397c7c232)
![image](https://github.com/Moonlight-Panel/Moonlight/assets/94371018/fd27a839-6eb9-49d9-9e33-3248d3c90e09)

**Comment by Masu-Baumgartner** [comment]
Invalid steps to reproduce + missing logs

**Comment by gOOvER** [comment]
i think, he didnt add --skip-lets-encrypt
i had the same issue, when a cert allready issued.

**Comment by jesperrichert** [comment]
> Invalid steps to reproduce + missing logs

Hi masu sorry but i only have this and to the deamon error or not set the data i have no logs sorry!

**Comment by jesperrichert** [comment]
(But the error i have now every time!) with the server if i have recreate it

**Comment by gOOvER** [comment]
> (But the error i have now every time!) with the server if i have recreate it

same server panel and daemon?

**Comment by jesperrichert** [comment]
yes

**Comment by Masu-Baumgartner** [comment]
The daemon has logs, you didnt attach it => invalid issue

**Comment by jesperrichert** [comment]
ok sec i send

**Comment by jesperrichert** [comment]
![image](https://github.com/Moonlight-Panel/Moonlight/assets/94371018/e8908d0b-9d1c-4682-8b89-f82225ebe871)
