### ISSUE TITLE
V2EA/Deleting an image is not possible

### ISSUE THREAD

**Issue by gOOvER** [Moonlight-Panel/Moonlight#385]
### Current Behavior

you are not able to delete an image.

### Expected Behavior

able to delete an image

### Steps to Reproduce

- create an image
- save it
- try to delete it

### Panel Version

2.0.0

### Daemon Version

2.0.0

### Wings Version

none

### Error Logs

```bash
nothing in the logs
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
Fixed in #387
