### ISSUE TITLE
Console output random

### ISSUE THREAD

**Issue by lonewolf3321** [Moonlight-Panel/Moonlight#405]
### Current Behavior

the console still random random output like in this image. and it can't properly shows the correct output. like when it download dependencies. and it can't show the proper qr code.
![Screenshot (71)](https://github.com/Moonlight-Panel/Moonlight/assets/147096600/3cec63d4-671b-477d-a61c-8d2dd48a87d4)
![Screenshot (70)](https://github.com/Moonlight-Panel/Moonlight/assets/147096600/c8ceb58f-3f9d-49fd-8bd5-8a334b6c225d)

### Expected Behavior

i know this must be in the feature section but, can you make the console a little bit bigger, so it can show the qr code properly

### Steps to Reproduce

i just click start? i mean its in console : )

### Panel Version

1.4.0

### Daemon Version

1.42

### Wings Version

1.4.2

### Games and/or Images Affected

none

### Docker Image

ghcr.io/parkervcp/yolks:nodejs_19

### Error Logs

```bash
there is no error log. everything run normal. it just the console.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment]
Use V2 EA. Its fixed there

**Comment by Masu-Baumgartner** [comment]
This is v2 ea

**Comment by gOOvER** [comment]
![msedge_Jg1aM2ZU8G](https://github.com/Moonlight-Panel/Moonlight/assets/116325/8aed558e-15cd-452d-ba89-23ed7e3a07a8)

**Comment by Masu-Baumgartner** [comment]
The screenshot is from v2 though

**Comment by mxritzdev** [comment]
and we havent got specific version numbers right now

**Comment by Masu-Baumgartner** [comment]
+ dont use wings

**Comment by gOOvER** [comment]
> and we havent got specific version numbers right now

![Tabby_ydE2Jq0JNM](https://github.com/Moonlight-Panel/Moonlight/assets/116325/1b070e03-3974-4e76-b714-47b7f4436c55)

**Comment by jesperrichert** [comment]
Yes this is the v2 but the v2 has no other Versions....

**Comment by mxritzdev** [comment]
thanks jesper

**Comment by gOOvER** [comment]
Senseless discussion ;)

See both screens

**Comment by gOOvER** [comment]
> thanks jesper

offtopic

**Comment by gOOvER** [comment]
That's exactly what I meant in the past; always having the last word with pointless comments. Nothing has changed.

Look at the report; then look at the screen;

If anyone uses v2, they should know that too. but I'm not going to start another discussion here.

**Comment by mxritzdev** [comment]
> always having the last word

you are currently discussing, this issue is closed and this type of comments are useless

**Comment by Masu-Baumgartner** [comment]
Guys... people stop it. goover already said he does not want to start a discussion so please stop writing then in an issue which is already closed @Moritz-Deiaco
