### ISSUE TITLE
Admin Dashboard Links are wrong

### ISSUE THREAD

**Issue by Masu-Baumgartner** [Moonlight-Panel/Moonlight#409]
### Current Behavior

The links go to the wrong page

### Expected Behavior

The links shold point to the correct page

### Steps to Reproduce

Run moonllight and go to the admin dashboard

### Panel Version

v2 EA

### Daemon Version

v2 EA

### Wings Version

Imagine wings

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
![image](https://github.com/Moonlight-Panel/Moonlight/assets/68913099/03ee58af-0399-42df-b185-cfda85e9963b)

**Comment by Masu-Baumgartner** [comment]
And maybe use the StatCard component with an a tag around it so the ui looks the same as in every other stat page

**Comment by mxritzdev** [comment]
Fixed in #410
