### ISSUE TITLE
Server time

### ISSUE THREAD

**Issue by skynett81** [Moonlight-Panel/Moonlight#437]
### Current Behavior

The time on the servers does resett it self when you use the sidemenu like Dashboard,servers and so on.

Online (0h 0m 11s)

### Expected Behavior

Not resett before the server is restarting og starting

### Steps to Reproduce

The time on the servers does resett it self when you use the sidemenu like Dashboard,servers and so on.

Online (0h 0m 11s)

### Panel Version

v2EA

### Daemon Version

V2EA

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
This isnt an uptime counter (yet) and only shows the time since the last state update has been received
